### ISSUE TITLE
Add automated testing for org.geppetto.testbackend (includes a dependency on persistence bundle)

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto.persistence#11]
- [ ] Have one docker container corresponding to no persistence  (core+frontend+simulation+neuroml) built on every push from travis (see [this](https://github.com/VirtualFlyBrain/VFB2/blob/master/.travis.yml))
- [ ] Have one docker container corresponding to persistence configuration (core+frontend+simulation+neuroml+persistence+simulator.external) built on every push (see [this](https://github.com/VirtualFlyBrain/VFB2/blob/master/.travis.yml))

Required for the container:
- [ ] Install mySQL on the docker container (required by persistence)
- [ ] Install NEURON on the docker container (required by simulator.external)
- [ ] mvn install of testbackend needs to pass (i.e. JUnit tests pass on travis)
- [ ] Run casper tests on at least ONE configuration of bundles 
- [ ] Put the log file from the virgo server to show up in the travis-ci log when there is a failure
- [ ] Any push to development of testbackend will trigger the above

**Comment by tarelli** [comment]
@slarson update the list above!

**Comment by slarson** [comment]
I propose to break this card down, as there is [now](https://travis-ci.org/openworm/org.geppetto.persistence/builds/189551992) significant chunks of this functionality working, but the other items in the checklist will need significant more work and may not even really be necessary.  Currently the testing is being demoed with org.geppetto.persistence rather than org.geppetto.backend.  We should have a discussion about how to move forward in an iterative fashion.

**Comment by tarelli** [comment]
@gidili can you recognise [that failure](https://travis-ci.org/openworm/org.geppetto.persistence/builds/189551992) in casper? They all worked locally last time I checked. @slarson we can split the cards but having everything working in automated way on push (build included) is still something I want to achieve. If you could detail what steps are missing and what problems you encountered then it would be easy to move forward, also having all the details written down would make it easy for somebody to jump on whatever is left and help out. Thanks!

**Comment by slarson** [comment]
* Dependencies within travis to get any push on development branch of any geppetto backend to trigger a build on testbackend.
* Put the log file from the virgo server to show up in the travis-ci log when there is a failure
* Test the tests on localhost and compare to version on travis-ci
* Tests that work with a bundle built with VFB extension
* Tests that work with a bundle built with OSB extension
* Ensure that success of travis-ci tests makes the travis build succeed

**Comment by tarelli** [comment]
@slarson Thanks, incorporated that above and created new cards, see https://github.com/openworm/org.geppetto.testbackend/issues/52 https://github.com/openworm/org.geppetto.frontend/issues/531 https://github.com/openworm/org.geppetto.frontend/issues/530 https://github.com/openworm/org.geppetto.frontend/issues/529 
https://github.com/openworm/org.geppetto/issues/547
