### ISSUE TITLE
Persisting to S3 fails with Java SDK greater or equals than 1.8u60

### ISSUE THREAD

**Issue by adrianq** [openworm/org.geppetto.persistence#13]
It fails throwing the following exception:
Error reading request, ignored com.amazonaws.services.s3.model.AmazonS3Exception: AWS authentication requires a valid Date or x-amz-date header (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: F42548EEEB5497B7)

I don't know if this is sth we would like to tackle but at least I want to create the issue just in case someone else has this problem. [More info](http://stackoverflow.com/questions/32058431/aws-java-sdk-aws-authentication-requires-a-valid-date-or-x-amz-date-header)

**Comment by tarelli** [comment]
For reference https://github.com/aws/aws-sdk-java/issues/484

**Comment by tarelli** [comment]
@mattearnshaw try upgrading to the lastest version https://mvnrepository.com/artifact/org.apache.servicemix.bundles/org.apache.servicemix.bundles.aws-java-sdk/1.11.49_1 in the pom file of core and see if the error goes away?

**Comment by mattearnshaw** [comment]
@tarelli yes, it goes away with this artifact.

**Comment by tarelli** [comment]
@mattearnshaw great, can you create a PR? Thanks!
